version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.bak
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

default_expiration: "2s"

automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50


handlers:
- url: /datastore.*
  script: datastore.app
- url: /memcache.*
  script: memcache.app
- url: /task.*
  script: taskqueue.app

