runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.bak
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: firetactoe.app
  login: required
